### PR TITLE
fixing the build and test as discribed in #31

### PR DESCRIPTION
**Pull request by marc-portier**
This PR takes a stab at making the ```make all``` and its dependencies work again.

As such it also includes a fix for #31

### CODE REVIEW

**Comment by andreztz** [comment]
@marc-portier 

https://github.com/andreztz/pyradios/blob/ed9887182a78bb58e06d2d9291ef3ba385a30c1f/pyradios/__init__.py#

L6 E222 multiple spaces after operator @marc-portier

https://github.com/andreztz/pyradios/blob/ed9887182a78bb58e06d2d9291ef3ba385a30c1f/tests/test_radio_browser.py#L144

N806 variable 'EXPECTED_STATION_KEYS' in function should be lowercase

**Comment by marc-portier** [comment]
@andreztz, thx for the feedback --> maybe we should make sure that ```make check``` produces those errors too ?

**Comment by andreztz** [comment]
> @andreztz, thx for the feedback --> maybe we should make sure that `make check` produces those errors too ?

@marc-portier This will be extremely useful.

**Comment by marc-portier** [comment]
> > @andreztz, thx for the feedback --> maybe we should make sure that `make check` produces those errors too ?
> 
> @marc-portier This will be extremely useful.

registered the idea under #38

**Pull request merged**
