### PR TITLE
implementation for feature suggestion " facet browser" from issue #32

### PR DESCRIPTION
**Pull request by marc-portier**
provides fix for #32

### CODE REVIEW

**Comment by andreztz** [comment]
@marc-portier I ran the tests with the debugger and got the following result:

```
>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/ztz/Workspace/repos/github/pyradios/.venv/lib/python3.9/site-packages/_pytest/capture.py(217)read()
-> raise OSError(
(Pdb) ll
216  	   def read(self, *args):
217  ->	       raise OSError(
218  	           "pytest: reading from stdin while output is captured!  Consider using `-s`."
219  	       )
(Pdb) l
212  	
213  	class DontReadFromInput:
214  	   encoding = None
215  	
216  	   def read(self, *args):
217  ->	       raise OSError(
218  	           "pytest: reading from stdin while output is captured!  Consider using `-s`."
219  	       )
220  	
221  	   readline = read
222  	   readlines = read
(Pdb) q


=================================== short test summary info ===================================
FAILED tests/test_radio_facets.py::test_facet_init - OSError: pytest: reading from stdin whi...
!!!!!!!!!!!!!!!!!!!!!!!!!! _pytest.outcomes.Exit: Quitting debugger !!!!!!!!!!!!!!!!!!!!!!!!!!!

```
The solution is to add the `-s` flag when running the 'pytest` command.

**Comment by marc-portier** [comment]
@andreztz I don't quite catch how to reproduce this myself, and thus fail to see what I can do to fix

I know I've added logging to the test and have chosen to put those out to stdout ONLY if you call the test directly
``` python tests/test-radio-facets.py``` --> see the __main__ 

Assuming that is the culprit, there are some things I could do:
* remove all log.** stuff
* redirect log output to file
* allow args to __main__ to set debug-level or output + choose for a silent default
* and/or drive above settings through sys.env settings

wdyt?

**Comment by andreztz** [comment]
@marc-portier for now remove all the `log.**` from the code. I think this solves the problem.

**Comment by andreztz** [comment]
@marc-portier It seems to be an intermittent problem, because some responses provided by the upstream API do not contain any values associated with `tags`.

bug

Any idea how to solve this?

**Comment by marc-portier** [comment]
think this last fix does the job

**Pull request merged**
